### ISSUE TITLE
Left panel display problems

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/talk#381]
I'm on Version 0.40.2 (Intel).
Monterey 12.6.2.

Resizing the window of Nota will often result in a visual collapse of the left column (with cut off space and wrongly placed buttons).

Not related to tabs, as this also happens when only one tab is open.

![b1k10f](https://user-images.githubusercontent.com/1950766/222961441-421dda9a-7f6b-498e-891b-a01081389b20.png)
![c2t4w](https://user-images.githubusercontent.com/1950766/222961442-6257ebfb-9c2a-472e-8a0f-64363f29f011.png)

Previous report (closed back then because tabs related): #366

**Comment by astoilkov** [comment]
@minthemiddle We tried to replicate this on Monterey but couldn't. Some extra information would be helpful:
- Do you have steps you know that consistently reproduce this or maybe it seems to happen randomly?
- Is this new? In what version did it start happening?
- Can you record a video? (only if it's easy for you)

**Comment by luvs** [comment]
Same problem on Ventura. It's reproduce consistently, you just have to reduce the width of the window.

<img width="218" alt="Screenshot 2023-03-13 at 21 06 11" src="https://user-images.githubusercontent.com/731500/224774168-c5399376-0386-4a35-8477-9c2d4b9e4b68.png">

**Comment by Auratelience** [comment]
Same problem. I can consistently reproduce this.

Only occurs when the left sidebar is closed (ie. The toolbar just has all open tabs). File viewers have no issues at any size.

**Comment by astoilkov** [comment]
We are replicating what @luvs is experiencing but not @minthemiddle (the text is a lot more overlapped over the buttons).

We will fix the problem we see and hope to fix all cases.

**Comment by astoilkov** [comment]
I just published a new release. This issue should now be fixed.

I'm closing this but let me know if there are still problems.

Thanks for reporting!

**Comment by Auratelience** [comment]
Just installed the update (v40.3) and the problem remains.
<img width="495" alt="Nota" src="https://user-images.githubusercontent.com/75990319/227840162-4a0f3c6c-6c51-439c-a8df-b4d4c9281b12.png">

Thanks

**Comment by astoilkov** [comment]
@Auratelience We actually released 0.40.4 yesterday. Aren't you getting the update?
